name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          npm i
      - name: Run script
        run: |
          npm run init-db
          npm run fetch-milestone
          npm run fetch-history
          sleep 3
          npm run fetch-history
          npm run gen-html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-web
          path: web
          retention-days: 10
