name: Fetch Milestone

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  fetch:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          npm i
      - name: Update
        run: |
          export TURSO_TOKEN=${{ secrets.TURSO_TOKEN }}
          export URL=libsql://zig-jiacai2050.turso.io
          npm run fetch-history
