name: Init Database

on:
  workflow_dispatch:

env:
  TURSO_DB_URL: "libsql://zig-jiacai2050.turso.io"
  TURSO_TOKEN: "${{ secrets.TURSO_TOKEN }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  init:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          npm i
      - name: init
        run: |
          npm run init-db
